<?php /** @var $block \Mtools\AdminLog\Block\File\View */ ?>
<style>
    .admin__page-section-item-title a{
        color: #333;
        float: left;
        margin-top: -5px;
        margin-right: 25px;
        padding: 5px 15px;
        border: 2px solid #333;
        border-radius: 3px;
        font-size: 16px;
        font-weight: bold;
    }
    .admin__page-section-item-content td{
        max-width: 85vw;
    }
    .admin__page-section-item-content h3{
        margin-bottom: 10px;
    }
    .admin__page-section-item-content pre{
        margin: 0 0 2vw 2vw;
        overflow: auto;
        width: 85vw;
    }
    .admin__page-section-item-content.controls{
        border: 1px solid #333;
        margin-bottom: 40px;
        padding: 5px 10px;
    }
    .admin__page-section-item-content-action{
        display: inline-block;
    }
    .limit{
        float: left;
    }
    .pager{
        float: right;
    }
    .clearfix{
        clear: both;
    }
</style>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title">
            <span class="title"><?php echo $block->getFileName() ?></span>
            <a href="<?php echo $block->getBackUrl() ?>">Back</a>
        </div>
        <div class="admin__page-section-item-content">
            <pre><?php //echo $block->getLogFile() ?></pre>
        </div>
        <div class="admin__page-section-item-content controls">
            <div class="admin__page-section-item-content-action limit">
                <span class="label"><?php echo __('Lines to show') ?>: </span>
                <?php foreach ($block->getLimits() as $limit): ?>
                    <?php if ($limit == $block->getLimit()): ?>
                        <span><?php echo $limit ?></span>
                    <?php else: ?>
                        <a href="<?php echo $block->getLimitUrl($limit); ?>"><?php echo $limit ?></a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="admin__page-section-item-content-action pager">
                <span class="label"><?php echo __('Start from line') ?>: </span>
                <?php $i = 0; ?>
                <?php foreach ($block->getStarts() as $start): ?>
                    <?php if ($start == $block->getStart()): ?>
                        <span><?php echo $start ?></span>
                    <?php else: ?>
                        <a href="<?php echo $block->getStartUrl($start); ?>"><?php echo $start ?></a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="admin__page-section-item-content">
            <table>
            <?php foreach ($block->getLogFileBlocks() as $time => $logBlock): ?>
                <tr>
                    <td style="vertical-align: top">
                        <h3><?php echo $time; ?></h3>
                        <pre><?php echo str_replace("\n\n", "\n", $logBlock); ?></pre>
                    </td>
                </tr>
            <?php endforeach; ?>
            </table>
        </div>
        <div class="admin__page-section-item-content controls">
            <div class="admin__page-section-item-content-action limit">
                <span class="label"><?php echo __('Lines to show') ?>: </span>
                <?php foreach ($block->getLimits() as $limit): ?>
                    <?php if ($limit == $block->getLimit()): ?>
                        <span><?php echo $limit ?></span>
                    <?php else: ?>
                        <a href="<?php echo $block->getLimitUrl($limit); ?>"><?php echo $limit ?></a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="admin__page-section-item-content-action pager">
                <span class="label"><?php echo __('Start from line') ?>: </span>
                <?php $i = 0; ?>
                <?php foreach ($block->getStarts() as $start): ?>
                    <?php if ($start == $block->getStart()): ?>
                        <span><?php echo $start ?></span>
                    <?php else: ?>
                        <a href="<?php echo $block->getStartUrl($start); ?>"><?php echo $start ?></a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</section>
